# Generated by Django 5.0.7 on 2025-08-25 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('prelim', '前哨战'), ('settlement', '结算赛'), ('final', 'Final'), ('qualifier', '选拔赛'), ('final_pre', 'Final预选')], max_length=20)),
                ('rounds', models.IntegerField(default=5)),
                ('group_count', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
            ],
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('room_code', models.CharField(blank=True, default='', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turf.group')),
            ],
            options={
                'unique_together': {('event', 'round_no', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('prelim', '前哨战'), ('qualifier', '选拔赛'), ('settlement', '赛段结算赛'), ('final_pre', 'Final预选'), ('final', 'Season Final')], max_length=20)),
                ('track_name', models.CharField(max_length=200)),
                ('ruleset_json', models.TextField(default='{}')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.season')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.stage'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pool', models.IntegerField(default=600)),
                ('base_amount', models.FloatField(default=0.0)),
                ('extra_bonus', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('event', 'round_no', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PublishedRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_no', models.IntegerField(default=1)),
                ('place', models.IntegerField()),
                ('is_npc', models.BooleanField(default=False)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.heat')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('heat', 'player', 'horse_no')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('qualified_flag', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
    ]
