# Generated by Django 5.0.7 on 2025-08-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='支持换行。可写少量HTML（如 <br>、<a>）。')),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_login', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
