# Generated by Django 5.0.7 on 2025-09-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('horse_index', models.IntegerField(default=1)),
                ('place', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player')),
            ],
            options={
                'unique_together': {('event', 'player', 'round_no', 'horse_index')},
            },
        ),
    ]
