# Generated by Django 5.0.7 on 2025-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_selfreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='honor_aupl_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='honor_loh96_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='honor_nxns_champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='honor_umaleague_season_champ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='honor_umaleague_stage_champ',
            field=models.BooleanField(default=False),
        ),
    ]
