# Generated by Django 5.0.7 on 2025-10-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_player_public_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='赛事标题')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/events/', verbose_name='赛事海报')),
                ('description', models.TextField(verbose_name='赛事简介')),
                ('event_date', models.DateField(verbose_name='赛事日期')),
                ('original_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turf.event', verbose_name='关联的系统赛事')),
            ],
            options={
                'verbose_name': '历届赛事',
                'verbose_name_plural': '历届赛事',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='PastChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/champions/', verbose_name='夺冠海报')),
                ('testimonial', models.TextField(verbose_name='夺冠感言')),
                ('gdoc_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='冠军战马Google文档链接')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.player', verbose_name='冠军选手')),
                ('past_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turf.pastevent', verbose_name='关联的历届赛事')),
            ],
            options={
                'verbose_name': '历届冠军',
                'verbose_name_plural': '历届冠军',
                'ordering': ['-past_event__event_date'],
            },
        ),
    ]
