# Generated by Django 5.0.7 on 2025-10-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0006_pastevent_pastchampion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='广告标题')),
                ('poster', models.ImageField(upload_to='posters/ads/', verbose_name='宣传海报')),
                ('url', models.URLField(blank=True, default='', max_length=1024, verbose_name='广告链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '宣传广告',
                'verbose_name_plural': '宣传广告',
                'ordering': ['-created_at'],
            },
        ),
    ]
