name: pg-backup

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 发 Release 必须

    steps:
      - name: Install PostgreSQL client & openssl
        run: sudo apt-get update && sudo apt-get -y install postgresql-client openssl

      - name: Dump database
        env:
          PG_URL: ${{ secrets.PG_URL }}
        run: |
          set -e
          TS=$(date -u +'%Y%m%d-%H%M%SZ')
          echo "TS=$TS" >> $GITHUB_ENV
          FILE="backup-$TS.dump"
          echo "FILE=$FILE" >> $GITHUB_ENV
          pg_dump --format=custom --no-owner --no-privileges --dbname="$PG_URL" -f "$FILE"

      - name: Encrypt backup (AES-256)  # 直接加密，没口令就报错
        env:
          PASSPHRASE: ${{ secrets.BACKUP_PASSPHRASE }}
        run: |
          set -e
          if [ -z "${PASSPHRASE}" ]; then
            echo "ERROR: BACKUP_PASSPHRASE secret is missing."; exit 1
          fi
          openssl enc -aes-256-cbc -pbkdf2 -salt -in "$FILE" -out "$FILE.enc" -pass env:PASSPHRASE
          rm "$FILE"
          echo "FILE=$FILE.enc" >> $GITHUB_ENV

      - name: Create GitHub Release with backup
        uses: softprops/action-gh-release@v2
        with:
          tag_name: db-backup-${{ env.TS }}
          name: DB backup ${{ env.TS }}
          files: ${{ env.FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ env.TS }}
          path: ${{ env.FILE }}
          retention-days: 90
